name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Using Eclipse Temurin for Java 21
          java-version: '21'
          cache: 'gradle' # Caching Gradle dependencies for faster builds

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test